netty:
  websocket-server:
    prefix: /ctrl
    port  : 9527
  tcp-client:
    timeout: 3000

positioning:
  media-ip  : 192.168.5.33
  media-port: 50000
  commands  :

    - "id"    : 0
      "high"  : [B321E800270101000000ECFF]
      "medium": [B321DA00270101000000DFFE]
      "low"   : [B321B800270101000000BEFD]
      "off"   : [B32175002701010000007DFB]

    - "id"    : 1
      "high"  : [B32103002701010001000500]
      "medium": [B321DB00270101000100DFFE]
      "low"   : [B321930027010100010098FD]
      "off"   : [B321400027010100010047FB]

    - "id"    : 2
      "high"  : [B321F900270101000200FBFF]
      "medium": [B321DC00270101000200DFFE]
      "low"   : [B321940027010100020098FD]
      "off"   : [B32159002701010002005FFB]

    - "id"    : 3
      "high"  : [B321EB00270101000300ECFF]
      "medium": [B321CE00270101000300D0FE]
      "low"   : [B3219F00270101000300A2FD]
      "off"   : [B321640027010100030069FB]

web-panel:
  # 电脑
  computer:
    # 开机
    poweron:
      list:
        - "type"        : "host"
          "targetIp"    : "192.168.5.31"
          "targetPort"  : "6000"
          "welcome"     : "welcome_write_poweron"
          "pipeline"    : "pipeline_write_poweron"
          "global"      : "global_write_poweron"
          "future"      : "future_write_poweron"

        - "type"        : "leaderHost"
          "targetIp"    : "192.168.5.31"
          "targetPort"  : "6000"
          "1"           : "005_write_poweron"
          "2"           : "006_write_poweron"

        - "type"        : "hosts"
          "targetIp"    : "192.168.5.31"
          "targetPort"  : "6000"
          "all"         : "hosts_all_write_poweron"

        - "type"        : "medicine"
          "targetIp"    : "192.168.5.30"
          "targetPort"  : "6000"
          "1"           : "medicine_001_write_poweron"
          "2"           : "medicine_002_write_poweron"
          "3"           : "medicine_003_write_poweron"
          "4"           : "medicine_004_write_poweron"
          "5"           : "medicine_005_write_poweron"

        - "type"        : "global"
          "targetIp"    : "192.168.5.30"
          "targetPort"  : "6000"
          "1"           : "global_006_write_poweron"
          "2"           : "global_007_write_poweron"
          "3"           : "global_008_write_poweron"

        - "type"        : "integrated"
          "targetIp"    : "192.168.5.30"
          "targetPort"  : "6000"
          "all"         : "integrated_all_write_poweron"


    # 关机
    poweroff:
      list:
        - "type"    : "host"
          "port"    : "7788"
          "welcome" : "192.168.5.3"
          "pipeline": "192.168.5.4"
          "global"  : "192.168.5.5"
          "future"  : "192.168.5.6"

        - "type"    : "leaderHost"
          "port"    : "7788"
          "1"       : "192.168.5.11"
          "2"       : "192.168.5.12"

        - "type"    : "medicine"
          "port"    : "7788"
          "1"       : "192.168.5.13"
          "2"       : "192.168.5.14"
          "3"       : "192.168.5.15"
          "4"       : "192.168.5.16"
          "5"       : "192.168.5.17"

        - "type"    : "global"
          "port"    : "7788"
          "1"       : "192.168.5.18"
          "2"       : "192.168.5.19"
          "3"       : "192.168.5.20"

  # 音频处理器
  media:
    mode: positioning  # normal/positioning
    normal-command:
      - B321E800270101000000ECFF
      - B32103002701010001000500
      - B321F900270101000200FBFF
      - B321EB00270101000300ECFF
    media-ip: 192.168.5.33  # 同station下的ip和端口
    media-port: 50000
    mute:
      1: "B321FF002701020000000100"
      2: "B32100002701020001000100"
      3: "B32101002701020002000100"
      4: "B32102002701020003000100"
    unmute:
      1: "B321FE002701020000000000"
      2: "B321FF002701020001000000"
      3: "B32100002701020002000000"
      4: "B32101002701020003000000"

  # 继电器
  relay:
    ip      : 192.168.5.32
    port    : 6000
    command : "delay_all_write_{command}"

  # 灯带
  light:
    ip      : 192.168.5.32
    port    : 6000
    command : "light_{id}_write_{command}"

  # 领导来访的屏幕电源
  leader-screen:
    ip      : 192.168.5.32
    port    : 6000
    command : "leader-screen_{id}_write_{command}"

  # 领导来访的屏幕电源
  pipeline-screen:
    ip      : 192.168.5.32
    port    : 6000
    command : "pipline-screen_{id}_write_{command}"

  # 继电器下所有屏幕电源
  screen:
    ip      : 192.168.5.32
    port    : 6000
    command : "screen_all_write_{command}"

  # RGB led灯
  led:
    ip      : 192.168.5.60
    port    : 6000
    command : "light_{id}_write_{command}"

  # 大屏供电
  big-screen:
    list:
      - id      : global
        ip      : 192.168.5.61
        port    : 5000
        poweron : [000000000006000613ED00FF,000000000006000613EE00FF]
        poweroff: [000000000006000613ED00F0,000000000006000613EE00F0]

      - id      : welcome
        ip      : 192.168.5.62
        port    : 12345
        poweron : [0106002C000189C3]
        poweroff: [0106002C00004803]

      - id      : future
        ip      : 192.168.5.63
        port    : 5000
        poweron : [000000000006000613ED00FF]
        poweroff: [000000000006000613ED00F0]

  # 时序电源所有设备电源
  sequential:
    ip      : 192.168.5.60
    port    : 6000
    poweron : 880BFF
    poweroff: 880DFF

  # 音箱
  soundbox:
    ip      : 192.168.5.60
    port    : 6000
    command : "soundbox_write_{command}"

ip-name:
  map:
    "192.168.5.5" : "全球布局主机"
    "192.168.5.6" : "未来展望主机"
    "192.168.5.3" : "欢迎屏主机"
    "192.168.5.4" : "产品管线主机"
    "192.168.5.11": "领导来访主机01"
    "192.168.5.12": "领导来访主机02"
    "192.168.5.31": "8路开机管理器"

    "192.168.5.13": "药品展示一体机01"
    "192.168.5.14": "药品展示一体机02"
    "192.168.5.15": "药品展示一体机03"
    "192.168.5.16": "药品展示一体机04"
    "192.168.5.17": "药品展示一体机05"
    "192.168.5.18": "全球布局一体机01"
    "192.168.5.19": "全球布局一体机02"
    "192.168.5.20": "全球布局一体机03"
    "192.168.5.30": "10路开机管理器"

    "192.168.5.60": "485网关"
    "192.168.5.33": "音频处理器"
    "192.168.5.32": "继电器"

    "192.168.5.51": "uwb00"
    "192.168.5.52": "uwb01"
    "192.168.5.53": "uwb02"
    "192.168.5.54": "uwb03"

    "192.168.5.61": "全球布局大屏"
    "192.168.5.62": "欢迎大屏"
    "192.168.5.63": "未来展望大屏"

    "192.168.5.70": "ap01"
    "192.168.5.71": "ap02"
    "192.168.5.72": "ap03"
    "192.168.5.73": "ap04"

debug: true
logging:
  level:
    com.fall.nettyctrl.handler: debug