netty:
  websocket-server:
    prefix: /ctrl
    port: 9527

stations:
  media-ip: 192.168.5.33
  media-port: 50000
  commands:

    - "id"    : 0
      "high"  : 123
      "medium": 123
      "low"   : 123
      "off"   : 123

    - "id"    : 1
      "high"  : 123
      "medium": 123
      "low"   : 123
      "off"   : 123

    - "id"    : 2
      "high"  : B32142002B01010000003D04
      "medium": B3210E002B01010000000C01
      "low"   : B321AE002B0101000000AFFE
      "off"   : B3211D002B010100000021FB

    - "id"    : 3
      "high"  : 123
      "medium": 123
      "low"   : 123
      "off"   : 123

web-panel:
  computer:
    poweron:
      list:
        - type      : "host"
          targetIp  : "192.168.5.30"
          targetPort: "6000"
          welcome   : "192.168.5.3 :welcome"
          pipeline  : "192.168.5.4 :pipeline"
          global    : "192.168.5.5 :global"
          future    : "192.168.5.6 :future"

        - type      : "leaderHost"
          targetIp  : "192.168.5.30"
          targetPort: "6000"
          "1"       : "192.168.5.11:1"
          "2"       : "192.168.5.12:2"

        - type      : "medicine"
          targetIp  : "192.168.5.31"
          targetPort: "6000"
          "1"       : "192.168.5.13:1"
          "2"       : "192.168.5.14:2"
          "3"       : "192.168.5.15:3"
          "4"       : "192.168.5.16:4"
          "5"       : "192.168.5.17:5"

        - type      : "global"
          targetIp  : "192.168.5.31"
          targetPort: "6000"
          "1"       : "192.168.5.18:1"
          "2"       : "192.168.5.19:2"
          "3"       : "192.168.5.20:3"

    poweroff:

debug: true
logging:
  level:
    com.fall.nettyctrl.handler: debug