netty:
  websocket-server:
    prefix: /ctrl
    port: 9527

stations:
  media-ip: 192.168.5.33
  media-port: 50000
  commands:
    - "id": 0
      "high": 123
      "medium": 123
      "low": 123
      "off": 123
    - "id": 1
      "high": 123
      "medium": 123
      "low": 123
      "off": 123
    - "id": 2
      "high": B32142002B01010000003D04
      "medium": B3210E002B01010000000C01
      "low": B321AE002B0101000000AFFE
      "off": B3211D002B010100000021FB
    - "id": 3
      "high": 123
      "medium": 123
      "low": 123
      "off": 123

debug: true
logging:
  level:
    com.fall.nettyctrl.handler: debug