netty:
  websocket-server:
    prefix: /ctrl
    port: 9527

positioning:
  media-ip: 192.168.5.33
  media-port: 50000
  commands:

    - "id"    : 0
      "high"  : 123
      "medium": 123
      "low"   : 123
      "off"   : 123

    - "id"    : 1
      "high"  : 123
      "medium": 123
      "low"   : 123
      "off"   : 123

    - "id"    : 2
      "high"  : B32142002B01010000003D04
      "medium": B3210E002B01010000000C01
      "low"   : B321AE002B0101000000AFFE
      "off"   : B3211D002B010100000021FB

    - "id"    : 3
      "high"  : 123
      "medium": 123
      "low"   : 123
      "off"   : 123

web-panel:
  computer:
    # 开机
    poweron:
      list:
        - type      : "host"
          targetIp  : "192.168.5.30"
          targetPort: "6000"
          welcome   : "001_write_poweron"
          pipeline  : "002_write_poweron"
          global    : "003_write_poweron"
          future    : "004_write_poweron"

        - type      : "leaderHost"
          targetIp  : "192.168.5.30"
          targetPort: "6000"
          "1"       : "005_write_poweron"
          "2"       : "006_write_poweron"

        - type      : "medicine"
          targetIp  : "192.168.5.31"
          targetPort: "6000"
          "1"       : "001_write_poweron"
          "2"       : "002_write_poweron"
          "3"       : "003_write_poweron"
          "4"       : "004_write_poweron"
          "5"       : "005_write_poweron"

        - type      : "global"
          targetIp  : "192.168.5.31"
          targetPort: "6000"
          "1"       : "006_write_poweron"
          "2"       : "007_write_poweron"
          "3"       : "008_write_poweron"

    # 关机
    poweroff:
      list:
        - type    : "host"
          port    : "7788"
          welcome : "192.168.3.219"
          pipeline: "192.168.5.4"
          global  : "192.168.5.5"
          future  : "192.168.5.6"

        - type: "leaderHost"
          port: "7788"
          "1" : "192.168.5.11"
          "2" : "192.168.5.12"

        - type: "medicine"
          port: "7788"
          "1" : "192.168.5.13"
          "2" : "192.168.5.14"
          "3" : "192.168.5.15"
          "4" : "192.168.5.16"
          "5" : "192.168.5.17"

        - type: "global"
          port: "7788"
          "1" : "192.168.5.18"
          "2" : "192.168.5.19"
          "3" : "192.168.5.20"

# 音频处理器
media:
  mode: positioning  # normal/positioning
  normal-command: "123"
  media-ip: 192.168.5.33  # 同station下的ip和端口
  media-port: 50000
  gateway:
    ip: 192.168.5.34
    port: 6000
    poweron: "123"
    poweroff: "123"
  mute:
    1: "123"
    2: "123"
    3: "123"
    4: "123"
  unmute:
    1: "123"
    2: "123"
    3: "123"
    4: "123"

debug: true
logging:
  level:
    com.fall.nettyctrl.handler: debug